"""
interview_schema.py
===================
Pydantic schemas for the Interview Management Module.

Covers:
  - Schedule creation / update payload
  - Individual slot item within a schedule
  - Result save payload (bulk upsert)
"""

from pydantic import BaseModel, Field
from typing import List, Optional


# =============================================================================
# Schedule — Create / Update
# =============================================================================


class SlotSaveItem(BaseModel):
    """
    One student's slot assignment, generated by scheduleEngine.ts on the frontend.

    For ALL_SIMULTANEOUS  : slot_time = start of the single shared slot
    For ALL_SEQUENTIAL    : slot_time = individual student's exact time
    For BATCH_SIMULTANEOUS: slot_time = batch start time; batch_number filled
    For BATCH_SEQUENTIAL  : slot_time = individual time within batch; both batch_number + seq_number filled
    """

    application_id: int = Field(..., description="FK → plm_application.application_id")
    slot_time: Optional[str] = Field(
        None, description="Datetime string 'YYYY-MM-DD HH:MM:SS'"
    )
    batch_number: Optional[int] = Field(
        None, description="Batch index (1, 2, 3…) — NULL for non-batch modes"
    )
    seq_number: Optional[int] = Field(
        None, description="Position within slot/batch — used for ordering"
    )
    interviewer_name: Optional[str] = Field(
        None, description="Interviewer name override for this slot"
    )
    interviewer_email: Optional[str] = Field(
        None, description="Interviewer email override for this slot"
    )
    # F2: structured FK references (optional — sent by wizard after Feature 1 fix)
    interviewer_id: Optional[int] = Field(
        None, description="FK → plm_company_contact.contact_id"
    )
    student_id: Optional[int] = Field(
        None, description="FK → iems_students.student_id (denormalised)"
    )
    contact_id: Optional[int] = Field(
        None, description="FK → plm_company_contact.contact_id"
    )


class ScheduleSavePayload(BaseModel):
    """
    Payload for POST /placement/interview/schedule/save (create)
                 PUT /placement/interview/schedule/save (update — schedule_id required)

    The frontend wizard (scheduleEngine.ts) generates the preview client-side.
    On Confirm, the full payload including all slots is sent here for persistence.
    """

    schedule_id: Optional[int] = Field(
        None,
        description="Provide for UPDATE; omit or set None for CREATE",
    )
    drive_id: int = Field(..., description="FK → plm_drive.drive_id")
    round_id: int = Field(..., description="FK → plm_drive_round.round_id")

    # Scheduling mode — 4 options from scheduleEngine
    scheduling_mode: str = Field(
        ...,
        description="BATCH_SIMULTANEOUS | BATCH_SEQUENTIAL | ALL_SIMULTANEOUS | ALL_SEQUENTIAL",
    )
    batch_size: Optional[int] = Field(
        None, description="Students per batch (batch modes only)"
    )
    duration_minutes: int = Field(..., description="Duration per slot / per batch in minutes")

    # Dates & venue
    start_date: str = Field(..., description="First interview date 'YYYY-MM-DD'")
    end_date: Optional[str] = Field(None, description="Last interview date 'YYYY-MM-DD'")
    venue_type: str = Field(..., description="PHYSICAL | VIRTUAL")
    venue_details: Optional[str] = Field(None, description="Hall / room / address")
    meeting_link: Optional[str] = Field(None, description="Zoom / Meet link for VIRTUAL")

    # Interviewer info (comma-separated if multiple)
    interviewer_names: Optional[str] = Field(None, description="Comma-separated interviewer names")
    interviewer_email: Optional[str] = Field(None, description="Comma-separated interviewer emails")

    # Totals — computed by frontend scheduleEngine, stored for quick display
    total_students: int = Field(..., ge=1)
    total_slots: int = Field(..., ge=1)
    days_required: int = Field(..., ge=1)

    # All student slots from the preview
    slots: List[SlotSaveItem] = Field(..., min_items=1)


# =============================================================================
# Round Result — Bulk Save
# =============================================================================


class ResultSaveItem(BaseModel):
    application_id: int = Field(..., description="FK → plm_application.application_id")
    round_id: int = Field(..., description="FK → plm_drive_round.round_id")
    result: str = Field(
        ..., description="PASS | FAIL | HOLD | ABSENT"
    )
    feedback_notes: Optional[str] = Field(None, description="Interviewer's notes / remarks")


class ResultBulkSavePayload(BaseModel):
    """
    Payload for POST /placement/interview/result/save.
    Backend uses INSERT ... ON DUPLICATE KEY UPDATE via the
    UNIQUE KEY uq_application_round (application_id, round_id) on plm_round_result.
    """

    results: List[ResultSaveItem] = Field(..., min_items=1)


# =============================================================================
# Round Result — Single Override
# =============================================================================


class ResultOverridePayload(BaseModel):
    """
    Payload for PATCH /placement/interview/result/override.
    Used by TPO to correct a previously-saved result for a single candidate.
    """

    result_id: int = Field(..., description="PK of plm_round_result row to update")
    result: str = Field(..., description="PASS | FAIL | HOLD | ABSENT")
    feedback_notes: Optional[str] = Field(None, description="Updated notes / remarks")

